### ISSUE TITLE
 exdate[name].toISOString

### ISSUE THREAD

**Issue by romibe** [eouia/MMM-CalendarExt#46]
Hi,
It came with new version last week. I think its about returnung appointments in the exchange ical. 
Thank you.

Whoops! There was an uncaught exception...
TypeError: exdate[name].toISOString is not a function
    at Object.EXDATE (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/ical.js:200:35)
    at Object.handleObject (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/ical.js:379:41)
    at Object.parseICS (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/ical.js:420:20)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/node-ical.js:18:23)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)

**Comment by eouia** [comment]
Can I get your ical url for analysis?

**Comment by romibe** [comment]
Thank you for quick reply. Unfort. its my bussiness exchange ical. I understand the issue its useless without ical, but may be others have same issue und can share.
thank you for great work.

**Comment by eouia** [comment]
The error might be caused `recurrence event rule with exception`. I think there might be a non-standard formatted field in that iCal. However, I should know what kind of it to fix that.
I'll close this issue at this moment, But I'll behold this issue regularly
